In [296]:
import pandas as pd

In [297]:
df=pd.read_csv('../data/raw/MP_Districts_MODIS_Monthly_LST_Final_Fixed.csv')

In [298]:
df.head()

   district_code     district    year  month        lst  night_lst
0          17728  Hoshangabad  2017.0    1.0  23.831029  15.870616
1          17730     Jabalpur  2017.0    1.0  25.737332  12.858634
2          17732       Mandla  2017.0    1.0  26.466007  15.242156
3          17733     Mandsaur  2017.0    1.0  23.918397  13.274276
4          17734       Morena  2017.0    1.0  21.645031  12.032893

In [299]:
print(df.shape)

(5114, 6)

In [300]:
print(df.isnull().sum())

district_code    0
district         0
year             0
month            0
lst              0
night_lst        0
dtype: int64

In [301]:
print(df.duplicated().sum())

0

In [302]:
df.describe()

       district_code         year        month          lst    night_lst
count    5114.000000  5114.000000  5114.000000  5114.000000  5114.000000
mean    28367.673054  2020.999413     6.497849    33.005163    19.755426
std     21085.732876     2.578894     3.451955     7.293573     4.554592
min     17712.000000  2017.000000     1.000000    16.542069     4.163208
25%     17726.000000  2019.000000     3.000000    27.716907    16.384368
50%     17741.000000  2021.000000     6.000000    31.343274    20.458071
75%     17754.000000  2023.000000     9.000000    38.802220    23.136426
max     70177.000000  2025.000000    12.000000    50.732071    30.694482

In [303]:
df['lst'].describe()
df['night_lst'].describe()

count    5114.000000
mean       19.755426
std         4.554592
min         4.163208
25%        16.384368
50%        20.458071
75%        23.136426
max        30.694482
Name: night_lst, dtype: float64

In [304]:
df['lst'].describe()

count    5114.000000
mean       33.005163
std         7.293573
min        16.542069
25%        27.716907
50%        31.343274
75%        38.802220
max        50.732071
Name: lst, dtype: float64

In [305]:
lst = df.copy()

In [306]:
print(lst)

      district_code     district    year  month        lst  night_lst
0             17728  Hoshangabad  2017.0    1.0  23.831029  15.870616
1             17730     Jabalpur  2017.0    1.0  25.737332  12.858634
2             17732       Mandla  2017.0    1.0  26.466007  15.242156
3             17733     Mandsaur  2017.0    1.0  23.918397  13.274276
4             17734       Morena  2017.0    1.0  21.645031  12.032893
...             ...          ...     ...    ...        ...        ...
5109          17751        Sidhi  2025.0   12.0  18.102727  10.910930
5110          17753    Tikamgarh  2025.0   12.0  18.867405  11.188649
5111          17754       Ujjain  2025.0   12.0  20.127507  14.644286
5112          17755      Vidisha  2025.0   12.0  21.092234  13.482417
5113          70171    Burhanpur  2025.0   12.0  23.119095  15.561875

[5114 rows x 6 columns]

In [307]:
lst_sorted = lst.sort_values(by=['district','year','month'], ascending=True)
print(lst_sorted)

      district_code    district    year  month        lst  night_lst
17            70168     Anuppur  2017.0    1.0  26.451292  13.692631
110           70168     Anuppur  2017.0    3.0  38.603106  15.254827
204           70168     Anuppur  2017.0    5.0  45.139231  24.177578
251           70168     Anuppur  2017.0    6.0  40.775629  23.654488
299           70168     Anuppur  2017.0    7.0  31.159059  21.178943
...             ...         ...     ...    ...        ...        ...
4883          17756  West Nimar  2025.0    8.0  29.590540  21.820982
4931          17756  West Nimar  2025.0    9.0  28.073994  22.077064
4979          17756  West Nimar  2025.0   10.0  29.365097  20.178533
5027          17756  West Nimar  2025.0   11.0  26.523911  17.997143
5074          17756  West Nimar  2025.0   12.0  23.339348  14.665141

[5114 rows x 6 columns]

In [308]:
lst_sorted.to_csv("../data/raw/sorted_lst_for_MP.csv", index=False)

In [309]:
lst_sorted = lst_sorted.astype({"year": int, "month": int})
lst_sorted.dtypes

district_code      int64
district             str
year               int64
month              int64
lst              float64
night_lst        float64
dtype: object

In [310]:
lst_sorted.describe()

       district_code         year        month          lst    night_lst
count    5114.000000  5114.000000  5114.000000  5114.000000  5114.000000
mean    28367.673054  2020.999413     6.497849    33.005163    19.755426
std     21085.732876     2.578894     3.451955     7.293573     4.554592
min     17712.000000  2017.000000     1.000000    16.542069     4.163208
25%     17726.000000  2019.000000     3.000000    27.716907    16.384368
50%     17741.000000  2021.000000     6.000000    31.343274    20.458071
75%     17754.000000  2023.000000     9.000000    38.802220    23.136426
max     70177.000000  2025.000000    12.000000    50.732071    30.694482

In [311]:
lst_sorted.dtypes

district_code      int64
district             str
year               int64
month              int64
lst              float64
night_lst        float64
dtype: object

In [312]:
lst_sorted.head()

     district_code district  year  month        lst  night_lst
17           70168  Anuppur  2017      1  26.451292  13.692631
110          70168  Anuppur  2017      3  38.603106  15.254827
204          70168  Anuppur  2017      5  45.139231  24.177578
251          70168  Anuppur  2017      6  40.775629  23.654488
299          70168  Anuppur  2017      7  31.159059  21.178943

In [313]:
lst_sorted.sample(10)

      district_code   district  year  month        lst  night_lst
3473          17726       Guna  2023      2  28.378847  17.506061
1960          17714      Betul  2020      6  36.276498  23.340567
4397          17744      Sagar  2024      9  29.957560  21.338441
1855          70174      Katni  2020      4  41.899774  21.799113
585           17714      Betul  2018      1  29.238610  14.471527
1616          70175    Neemuch  2019     11  29.766670  17.650607
1748          70171  Burhanpur  2020      1  27.708787  14.897822
1197          17716     Bhopal  2019      2  28.139398  15.967847
4275          70172    Dindori  2024      7  27.912461  20.873742
1103          17716     Bhopal  2018     12  24.366045  12.247504

In [314]:
builtup = pd.read_csv("../data/raw/MP_Districts_GHSL_BuiltUp_2015_2020_2025.csv")
builtup.head()

   district_code     district  year  built_up_area_sq_m  built_up_area_sq_km
0          17728  Hoshangabad  2015        3.820666e+07            38.206661
1          17730     Jabalpur  2015        5.626213e+07            56.262125
2          17732       Mandla  2015        2.616109e+07            26.161093
3          17733     Mandsaur  2015        4.746622e+07            47.466222
4          17734       Morena  2015        3.636720e+07            36.367198

In [315]:
builtup.describe()

       district_code         year  built_up_area_sq_m  built_up_area_sq_km
count     144.000000   144.000000        1.440000e+02           144.000000
mean    28659.041667  2020.000000        4.808269e+07            48.082692
std     21370.289607     4.096732        2.287779e+07            22.877790
min     17712.000000  2015.000000        1.393689e+07            13.936890
25%     17726.750000  2015.000000        3.236485e+07            32.364845
50%     17741.500000  2020.000000        4.603034e+07            46.030337
75%     17754.250000  2025.000000        5.838609e+07            58.386087
max     70177.000000  2025.000000        1.596124e+08           159.612405

In [316]:
builtup.isnull().sum()

district_code          0
district               0
year                   0
built_up_area_sq_m     0
built_up_area_sq_km    0
dtype: int64

In [317]:
builtup.sample(20)

     district_code    district  year  built_up_area_sq_m  built_up_area_sq_km
76           17723        Dhar  2020        8.582245e+07            85.822451
15           17726        Guna  2015        2.768375e+07            27.683750
10           70174       Katni  2015        4.290536e+07            42.905356
114          70169  Ashoknagar  2025        2.914199e+07            29.141986
42           17750    Shivpuri  2015        4.105492e+07            41.054917
123          17722       Dewas  2025        6.165824e+07            61.658239
99           17733    Mandsaur  2025        5.782582e+07            57.825825
12           70176     Sheopur  2015        1.558820e+07            15.588205
113          70168     Anuppur  2025        2.713994e+07            27.139942
39           17746      Sehore  2015        4.426337e+07            44.263374
141          17754      Ujjain  2025        7.427904e+07            74.279037
9            70173       Harda  2015        1.955832e+07            19.558324
143          70171   Burhanpur  2025        1.845755e+07            18.457545
135          17746      Sehore  2025        5.795186e+07            57.951860
140          17753   Tikamgarh  2025        4.737632e+07            47.376322
6            17756  West Nimar  2015        5.002419e+07            50.024194
52           17734      Morena  2020        4.748009e+07            47.480095
105          70173       Harda  2025        2.330550e+07            23.305495
109          70177      Umaria  2025        2.013224e+07            20.132237
53           17741     Rajgarh  2020        4.435423e+07            44.354234

In [318]:
import numpy as np
builtup.select_dtypes(include=[np.number]).columns

Index(['district_code', 'year', 'built_up_area_sq_m', 'built_up_area_sq_km'], dtype='str')

In [319]:
print(builtup.dtypes)

district_code            int64
district                   str
year                     int64
built_up_area_sq_m     float64
built_up_area_sq_km    float64
dtype: object

In [320]:
builtup.head(20)

    district_code     district  year  built_up_area_sq_m  built_up_area_sq_km
0           17728  Hoshangabad  2015        3.820666e+07            38.206661
1           17730     Jabalpur  2015        5.626213e+07            56.262125
2           17732       Mandla  2015        2.616109e+07            26.161093
3           17733     Mandsaur  2015        4.746622e+07            47.466222
4           17734       Morena  2015        3.636720e+07            36.367198
5           17741      Rajgarh  2015        3.743109e+07            37.431089
6           17756   West Nimar  2015        5.002419e+07            50.024194
7           70170      Barwani  2015        2.821191e+07            28.211905
8           70172      Dindori  2015        1.462363e+07            14.623631
9           70173        Harda  2015        1.955832e+07            19.558324
10          70174        Katni  2015        4.290536e+07            42.905356
11          70175      Neemuch  2015        2.904943e+07            29.049433
12          70176      Sheopur  2015        1.558820e+07            15.588205
13          70177       Umaria  2015        1.393689e+07            13.936890
14          17725   East Nimar  2015        3.571081e+07            35.710813
15          17726         Guna  2015        2.768375e+07            27.683750
16          17748      Shahdol  2015        4.732459e+07            47.324593
17          70168      Anuppur  2015        2.045566e+07            20.455660
18          70169   Ashoknagar  2015        2.219358e+07            22.193580
19          17712     Balaghat  2015        5.323103e+07            53.231031

In [321]:
builtup_sorted = builtup.sort_values(by=['district', 'year'], ascending=True)
print(builtup_sorted)
builtup_sorted.to_csv("../data/raw/sorted_builtup_pct_MP.csv", index=False)

     district_code    district  year  built_up_area_sq_m  built_up_area_sq_km
17           70168     Anuppur  2015        2.045566e+07            20.455660
65           70168     Anuppur  2020        2.373153e+07            23.731529
113          70168     Anuppur  2025        2.713994e+07            27.139942
18           70169  Ashoknagar  2015        2.219358e+07            22.193580
66           70169  Ashoknagar  2020        2.598354e+07            25.983542
..             ...         ...   ...                 ...                  ...
94           17755     Vidisha  2020        4.082487e+07            40.824875
142          17755     Vidisha  2025        4.522015e+07            45.220147
6            17756  West Nimar  2015        5.002419e+07            50.024194
54           17756  West Nimar  2020        5.759953e+07            57.599529
102          17756  West Nimar  2025        6.437506e+07            64.375056

[144 rows x 5 columns]

In [322]:
pop = pd.read_csv("../data/raw/MP_Districts_GHSL_Population_2015_2020_2025.csv")
pop.head(20)

    district_code     district  year  total_population
0           17728  Hoshangabad  2015      1.368610e+06
1           17730     Jabalpur  2015      2.334657e+06
2           17732       Mandla  2015      9.813256e+05
3           17733     Mandsaur  2015      1.389199e+06
4           17734       Morena  2015      2.165020e+06
5           17741      Rajgarh  2015      1.627257e+06
6           17756   West Nimar  2015      2.010712e+06
7           70170      Barwani  2015      1.598652e+06
8           70172      Dindori  2015      9.154025e+05
9           70173        Harda  2015      6.491618e+05
10          70174        Katni  2015      1.804198e+06
11          70175      Neemuch  2015      8.255446e+05
12          70176      Sheopur  2015      8.050513e+05
13          70177       Umaria  2015      5.747626e+05
14          17725   East Nimar  2015      1.394198e+06
15          17726         Guna  2015      1.317079e+06
16          17748      Shahdol  2015      1.435137e+06
17          70168      Anuppur  2015      6.661919e+05
18          70169   Ashoknagar  2015      9.669591e+05
19          17712     Balaghat  2015      1.793698e+06

In [323]:
pop.describe()

       district_code         year  total_population
count     144.000000   144.000000      1.440000e+02
mean    28659.041667  2020.000000      1.753986e+06
std     21370.289607     4.096732      7.079823e+05
min     17712.000000  2015.000000      5.747626e+05
25%     17726.750000  2015.000000      1.337940e+06
50%     17741.500000  2020.000000      1.682775e+06
75%     17754.250000  2025.000000      2.168971e+06
max     70177.000000  2025.000000      4.516985e+06

In [324]:
pop.dtypes

district_code         int64
district                str
year                  int64
total_population    float64
dtype: object

In [325]:
pop['total_population'] = pop['total_population'].astype(int)

In [326]:
pop.dtypes

district_code       int64
district              str
year                int64
total_population    int64
dtype: object

In [327]:
pop.head()

   district_code     district  year  total_population
0          17728  Hoshangabad  2015           1368609
1          17730     Jabalpur  2015           2334656
2          17732       Mandla  2015            981325
3          17733     Mandsaur  2015           1389199
4          17734       Morena  2015           2165019

In [328]:
pop_sorted = pop.sort_values(by = ['district','year'], ascending = True)
print(pop_sorted)

     district_code    district  year  total_population
17           70168     Anuppur  2015            666191
65           70168     Anuppur  2020            693794
113          70168     Anuppur  2025            720180
18           70169  Ashoknagar  2015            966959
66           70169  Ashoknagar  2020           1020983
..             ...         ...   ...               ...
94           17755     Vidisha  2020           1678606
142          17755     Vidisha  2025           1749894
6            17756  West Nimar  2015           2010711
54           17756  West Nimar  2020           2114802
102          17756  West Nimar  2025           2203341

[144 rows x 4 columns]

In [329]:
sorted_pop_for_MP = pop_sorted.to_csv("../data/raw/sorted_pop_for_MP.csv", index=False)

In [330]:
df = pd.read_csv('../data/raw/MP_District_Monthly_NDVI_2018_2025.csv')
df.head(20)

    district_code     district    year  month      ndvi
0           17728  Hoshangabad  2018.0    1.0  0.665819
1           17730     Jabalpur  2018.0    1.0  0.538563
2           17732       Mandla  2018.0    1.0  0.449119
3           17733     Mandsaur  2018.0    1.0  0.559629
4           17734       Morena  2018.0    1.0  0.511915
5           17741      Rajgarh  2018.0    1.0  0.567436
6           17756   West Nimar  2018.0    1.0  0.492113
7           70170      Barwani  2018.0    1.0  0.404214
8           70172      Dindori  2018.0    1.0  0.459787
9           70173        Harda  2018.0    1.0  0.678664
10          70174        Katni  2018.0    1.0  0.503623
11          70175      Neemuch  2018.0    1.0  0.479097
12          70176      Sheopur  2018.0    1.0  0.400550
13          70177       Umaria  2018.0    1.0  0.462713
14          17725   East Nimar  2018.0    1.0  0.468082
15          17726         Guna  2018.0    1.0  0.543903
16          17748      Shahdol  2018.0    1.0  0.406790
17          70168      Anuppur  2018.0    1.0  0.379674
18          70169   Ashoknagar  2018.0    1.0  0.595622
19          17712     Balaghat  2018.0    1.0  0.529833

In [331]:
df.sample(20)

      district_code    district    year  month      ndvi
434           17732      Mandla  2018.0   10.0  0.557107
601           17720       Damoh  2019.0    1.0  0.512823
3897          70173       Harda  2024.0   10.0  0.483175
2891          70175     Neemuch  2023.0    1.0  0.536715
273           17736       Panna  2018.0    6.0  0.288795
2119          70170     Barwani  2021.0    9.0  0.572946
4109          17727     Gwalior  2025.0    2.0  0.578030
1638          17756  West Nimar  2020.0   11.0  0.443005
2944          17748     Shahdol  2023.0    2.0  0.413627
2834          17732      Mandla  2022.0   12.0  0.529746
4388          17714       Betul  2025.0    8.0  0.447122
4417          17730    Jabalpur  2025.0    9.0  0.685861
462           17729      Indore  2018.0   10.0  0.378864
2441          17749    Shajapur  2022.0    3.0  0.338548
673           17730    Jabalpur  2019.0    3.0  0.418146
2386          17739      Raisen  2022.0    2.0  0.578024
1784          70172     Dindori  2021.0    2.0  0.452268
2925          17754      Ujjain  2023.0    1.0  0.765011
4187          70175     Neemuch  2025.0    4.0  0.237037
1274          17721       Datia  2020.0    3.0  0.583054

In [332]:
df.describe()

       district_code         year        month         ndvi
count    4608.000000  4608.000000  4608.000000  4608.000000
mean    28659.041667  2021.500000     6.500000     0.454898
std     21298.269075     2.291537     3.452427     0.137982
min     17712.000000  2018.000000     1.000000     0.125199
25%     17726.750000  2019.750000     3.750000     0.337621
50%     17741.500000  2021.500000     6.500000     0.465350
75%     17754.250000  2023.250000     9.250000     0.563404
max     70177.000000  2025.000000    12.000000     0.783827

In [333]:
df.dtypes

district_code      int64
district             str
year             float64
month            float64
ndvi             float64
dtype: object

In [334]:
ndvi_sorted = df.sort_values(by=['district','year','month'], ascending=True)
print(ndvi_sorted.sample(20))

      district_code     district    year  month      ndvi
1248          17728  Hoshangabad  2020.0    3.0  0.487263
1157          17741      Rajgarh  2020.0    1.0  0.705178
3598          17755      Vidisha  2024.0    3.0  0.356167
1035          17722        Dewas  2019.0   10.0  0.559185
3974          17745        Satna  2024.0   11.0  0.406646
2243          17742       Ratlam  2021.0   11.0  0.458989
4442          17721        Datia  2025.0    9.0  0.656069
2782          17755      Vidisha  2022.0   10.0  0.407729
2799          17726         Guna  2022.0   11.0  0.409130
4086          17756   West Nimar  2025.0    2.0  0.472551
1370          17721        Datia  2020.0    5.0  0.245044
3487          17731       Jhabua  2024.0    1.0  0.529681
466           17739       Raisen  2018.0   10.0  0.509430
3415          70170      Barwani  2023.0   12.0  0.480710
4291          17712     Balaghat  2025.0    6.0  0.311373
2564          17714        Betul  2022.0    6.0  0.375620
2379          17722        Dewas  2022.0    2.0  0.533456
4464          17728  Hoshangabad  2025.0   10.0  0.652498
715           17751        Sidhi  2019.0    3.0  0.381367
4106          17721        Datia  2025.0    2.0  0.724760

In [335]:
sorted_NDVI_for_MP = ndvi_sorted.to_csv('../data/raw/sorted_NDVI_for_MP.csv',index=False)

In [336]:
df1 = pd.read_csv('../data/raw/sorted_lst_for_MP.csv')
df2 = pd.read_csv('../data/raw/sorted_NDVI_for_MP.csv')
df_merged_1 = pd.merge(df1, df2, on=['district_code','year','month','district'], how='right')
df_merged_1[['year', 'month']] = df_merged_1[['year','month']].astype(int)

In [337]:
df_merged_1.dtypes

district_code      int64
district             str
year               int64
month              int64
lst              float64
night_lst        float64
ndvi             float64
dtype: object

In [338]:
df_merged_1.head(20)

    district_code district  year  month        lst  night_lst      ndvi
0           70168  Anuppur  2018      1        NaN        NaN  0.379674
1           70168  Anuppur  2018      2  31.022090  14.983734  0.347770
2           70168  Anuppur  2018      3  39.598072  19.056348  0.307356
3           70168  Anuppur  2018      4  42.478163  20.937356  0.270313
4           70168  Anuppur  2018      5  42.944661  23.263237  0.274777
5           70168  Anuppur  2018      6  38.789129  25.023293  0.383138
6           70168  Anuppur  2018      7  30.391037  24.055679  0.389486
7           70168  Anuppur  2018      8  30.913989  22.019084  0.489859
8           70168  Anuppur  2018      9  30.536769  21.382662  0.641759
9           70168  Anuppur  2018     10        NaN        NaN  0.535852
10          70168  Anuppur  2018     11  29.793593  12.921890  0.441124
11          70168  Anuppur  2018     12        NaN        NaN  0.396785
12          70168  Anuppur  2019      1        NaN        NaN  0.374438
13          70168  Anuppur  2019      2  30.329219  14.996980  0.351701
14          70168  Anuppur  2019      3  36.633443  18.512734  0.328425
15          70168  Anuppur  2019      4  42.920718  21.689455  0.286473
16          70168  Anuppur  2019      5  45.546204  24.590959  0.288462
17          70168  Anuppur  2019      6  42.550010  26.049268  0.331849
18          70168  Anuppur  2019      7  33.545285  21.609693  0.492996
19          70168  Anuppur  2019      8  29.224766  21.392086  0.522781

In [339]:
monthly_day_avg = (df_merged_1.groupby(["district_code","month"])['lst'].transform("mean"))
df_merged_1['lst'] = df_merged_1['lst'].fillna(monthly_day_avg)

In [340]:
monthly_night_avg = (df_merged_1.groupby(["district_code","month"])['night_lst'].transform("mean"))
df_merged_1['night_lst'] = df_merged_1['night_lst'].fillna(monthly_night_avg)

In [341]:
df_merged_1.head(20)

    district_code district  year  month        lst  night_lst      ndvi
0           70168  Anuppur  2018      1  24.049897  13.472585  0.379674
1           70168  Anuppur  2018      2  31.022090  14.983734  0.347770
2           70168  Anuppur  2018      3  39.598072  19.056348  0.307356
3           70168  Anuppur  2018      4  42.478163  20.937356  0.270313
4           70168  Anuppur  2018      5  42.944661  23.263237  0.274777
5           70168  Anuppur  2018      6  38.789129  25.023293  0.383138
6           70168  Anuppur  2018      7  30.391037  24.055679  0.389486
7           70168  Anuppur  2018      8  30.913989  22.019084  0.489859
8           70168  Anuppur  2018      9  30.536769  21.382662  0.641759
9           70168  Anuppur  2018     10  28.358063  20.087057  0.535852
10          70168  Anuppur  2018     11  29.793593  12.921890  0.441124
11          70168  Anuppur  2018     12  24.175561  12.442541  0.396785
12          70168  Anuppur  2019      1  24.049897  13.472585  0.374438
13          70168  Anuppur  2019      2  30.329219  14.996980  0.351701
14          70168  Anuppur  2019      3  36.633443  18.512734  0.328425
15          70168  Anuppur  2019      4  42.920718  21.689455  0.286473
16          70168  Anuppur  2019      5  45.546204  24.590959  0.288462
17          70168  Anuppur  2019      6  42.550010  26.049268  0.331849
18          70168  Anuppur  2019      7  33.545285  21.609693  0.492996
19          70168  Anuppur  2019      8  29.224766  21.392086  0.522781

In [342]:
import numpy as np
df3 = pd.read_csv('../data/raw/sorted_pop_for_MP.csv')
districts = df3[['district_code','district']].drop_duplicates()
years = list(range(2015,2026))
grid = []
for _, row in districts.iterrows():
    for year in years:
        grid.append({
            'district_code': row['district_code'],
            'district': row['district'],
            'year': year
        })
full_grid_df = pd.DataFrame(grid)
df3_expanded = pd.merge(full_grid_df,df3,on=['district_code','district','year'], how='left')
df3_expanded['total_population'] = (df3_expanded.groupby('district_code')['total_population'].transform(lambda x: x.interpolate(method='linear')))

In [343]:
df4 = pd.read_csv('../data/raw/sorted_builtup_pct_MP.csv')
districts = df4[['district_code','district']].drop_duplicates()
years = list(range(2015,2026))
grid = []
for _, row in districts.iterrows():
    for year in years:
        grid.append({
            'district_code': row['district_code'],
            'district': row['district'],
            'year': year
        })
full_grid_df1 = pd.DataFrame(grid)
df4_expanded = pd.merge(full_grid_df1,df4, on = ['district_code','district','year'], how = 'left')
df4_expanded['built_up_area_sq_m'] = (df4_expanded.groupby('district_code')['built_up_area_sq_m'].transform(lambda x: x.interpolate(method='linear')))
df4_expanded.head(20)

    district_code    district  year  built_up_area_sq_m  built_up_area_sq_km
0           70168     Anuppur  2015        2.045566e+07            20.455660
1           70168     Anuppur  2016        2.111083e+07                  NaN
2           70168     Anuppur  2017        2.176601e+07                  NaN
3           70168     Anuppur  2018        2.242118e+07                  NaN
4           70168     Anuppur  2019        2.307636e+07                  NaN
5           70168     Anuppur  2020        2.373153e+07            23.731529
6           70168     Anuppur  2021        2.441321e+07                  NaN
7           70168     Anuppur  2022        2.509489e+07                  NaN
8           70168     Anuppur  2023        2.577658e+07                  NaN
9           70168     Anuppur  2024        2.645826e+07                  NaN
10          70168     Anuppur  2025        2.713994e+07            27.139942
11          70169  Ashoknagar  2015        2.219358e+07            22.193580
12          70169  Ashoknagar  2016        2.295157e+07                  NaN
13          70169  Ashoknagar  2017        2.370957e+07                  NaN
14          70169  Ashoknagar  2018        2.446756e+07                  NaN
15          70169  Ashoknagar  2019        2.522555e+07                  NaN
16          70169  Ashoknagar  2020        2.598354e+07            25.983542
17          70169  Ashoknagar  2021        2.661523e+07                  NaN
18          70169  Ashoknagar  2022        2.724692e+07                  NaN
19          70169  Ashoknagar  2023        2.787861e+07                  NaN

In [344]:
df4_expanded['built_up_area_sq_km'] = df4_expanded['built_up_area_sq_m']/1000000

In [345]:
df4_expanded.head(20)

    district_code    district  year  built_up_area_sq_m  built_up_area_sq_km
0           70168     Anuppur  2015        2.045566e+07            20.455660
1           70168     Anuppur  2016        2.111083e+07            21.110834
2           70168     Anuppur  2017        2.176601e+07            21.766008
3           70168     Anuppur  2018        2.242118e+07            22.421182
4           70168     Anuppur  2019        2.307636e+07            23.076356
5           70168     Anuppur  2020        2.373153e+07            23.731529
6           70168     Anuppur  2021        2.441321e+07            24.413212
7           70168     Anuppur  2022        2.509489e+07            25.094894
8           70168     Anuppur  2023        2.577658e+07            25.776577
9           70168     Anuppur  2024        2.645826e+07            26.458259
10          70168     Anuppur  2025        2.713994e+07            27.139942
11          70169  Ashoknagar  2015        2.219358e+07            22.193580
12          70169  Ashoknagar  2016        2.295157e+07            22.951573
13          70169  Ashoknagar  2017        2.370957e+07            23.709565
14          70169  Ashoknagar  2018        2.446756e+07            24.467558
15          70169  Ashoknagar  2019        2.522555e+07            25.225550
16          70169  Ashoknagar  2020        2.598354e+07            25.983542
17          70169  Ashoknagar  2021        2.661523e+07            26.615231
18          70169  Ashoknagar  2022        2.724692e+07            27.246920
19          70169  Ashoknagar  2023        2.787861e+07            27.878609

In [346]:
df_merged1 = df_merged_1.to_csv('../data/raw/df_merged1.csv', index = False)

In [347]:
df = pd.read_csv('../data/raw/df_merged1.csv')
df.head()

   district_code district  year  month        lst  night_lst      ndvi
0          70168  Anuppur  2018      1  24.049897  13.472585  0.379674
1          70168  Anuppur  2018      2  31.022090  14.983734  0.347770
2          70168  Anuppur  2018      3  39.598072  19.056348  0.307356
3          70168  Anuppur  2018      4  42.478163  20.937356  0.270313
4          70168  Anuppur  2018      5  42.944661  23.263237  0.274777

In [348]:
months = list(range(1,13))
grid = []
for _,row in df3_expanded.iterrows():
    for month in months:
        grid.append({
            'district_code': row['district_code'],
            'district': row['district'],
            'year': row['year'],
            'month': month,
            'total_population': row['total_population'],
        })

In [349]:
full_grid_df2 = pd.DataFrame(grid)

In [350]:
full_grid_df2.head(20)

    district_code district  year  month  total_population
0           70168  Anuppur  2015      1          666191.0
1           70168  Anuppur  2015      2          666191.0
2           70168  Anuppur  2015      3          666191.0
3           70168  Anuppur  2015      4          666191.0
4           70168  Anuppur  2015      5          666191.0
5           70168  Anuppur  2015      6          666191.0
6           70168  Anuppur  2015      7          666191.0
7           70168  Anuppur  2015      8          666191.0
8           70168  Anuppur  2015      9          666191.0
9           70168  Anuppur  2015     10          666191.0
10          70168  Anuppur  2015     11          666191.0
11          70168  Anuppur  2015     12          666191.0
12          70168  Anuppur  2016      1          671711.6
13          70168  Anuppur  2016      2          671711.6
14          70168  Anuppur  2016      3          671711.6
15          70168  Anuppur  2016      4          671711.6
16          70168  Anuppur  2016      5          671711.6
17          70168  Anuppur  2016      6          671711.6
18          70168  Anuppur  2016      7          671711.6
19          70168  Anuppur  2016      8          671711.6

In [351]:
df3_final = pd.merge(full_grid_df2, df3_expanded, on=['district_code','district','year','total_population'], how='left')

In [352]:
final_pop = df3_final.to_csv('../data/raw/final_pop.csv', index=False)

In [353]:
df5 = pd.read_csv('../data/raw/final_pop.csv')

In [354]:
df5.head()

   district_code district  year  month  total_population
0          70168  Anuppur  2015      1          666191.0
1          70168  Anuppur  2015      2          666191.0
2          70168  Anuppur  2015      3          666191.0
3          70168  Anuppur  2015      4          666191.0
4          70168  Anuppur  2015      5          666191.0

In [355]:
df_with_pop = pd.merge(df, df5, on = ['district_code','district','year','month'],how='inner')

In [356]:
df_with_pop_and_ndvi = df_with_pop.to_csv('../data/raw/df_with_pop_and_ndvi.csv',index=False)

In [357]:
df6 = pd.read_csv('../data/raw/df_with_pop_and_ndvi.csv')

In [358]:
df6.head(20)

,district_code,district,year,month,lst,night_lst,ndvi,total_population
0,70168,Anuppur,2018,1,24.049897,13.472585,0.379674,682752.8
1,70168,Anuppur,2018,2,31.022090,14.983734,0.347770,682752.8
2,70168,Anuppur,2018,3,39.598072,19.056348,0.307356,682752.8
3,70168,Anuppur,2018,4,42.478163,20.937356,0.270313,682752.8
4,70168,Anuppur,2018,5,42.944661,23.263237,0.274777,682752.8
5,70168,Anuppur,2018,6,38.789129,25.023293,0.383138,682752.8
6,70168,Anuppur,2018,7,30.391037,24.055679,0.389486,682752.8
7,70168,Anuppur,2018,8,30.913989,22.019084,0.489859,682752.8
8,70168,Anuppur,2018,9,30.536769,21.382662,0.641759,682752.8
9,70168,Anuppur,2018,10,28.358063,20.087057,0.535852,682752.8
10,70168,Anuppur,2018,11,29.793593,12.921890,0.441124,682752.8
11,70168,Anuppur,2018,12,24.175561,12.442541,0.396785,682752.8
12,70168,Anuppur,2019,1,24.049897,13.472585,0.374438,688273.4
13,70168,Anuppur,2019,2,30.329219,14.996980,0.351701,688273.4
14,70168,Anuppur,2019,3,36.633443,18.512734,0.328425,688273.4
15,70168,Anuppur,2019,4,42.920718,21.689455,0.286473,688273.4
16,70168,Anuppur,2019,5,45.546204,24.590959,0.288462,688273.4
17,70168,Anuppur,2019,6,42.550010,26.049268,0.331849,688273.4
18,70168,Anuppur,2019,7,33.545285,21.609693,0.492996,688273.4
19,70168,Anuppur,2019,8,29.224766,21.392086,0.522781,688273.4

In [359]:
df4_expanded.head()

   district_code district  year  built_up_area_sq_m  built_up_area_sq_km
0          70168  Anuppur  2015        2.045566e+07            20.455660
1          70168  Anuppur  2016        2.111083e+07            21.110834
2          70168  Anuppur  2017        2.176601e+07            21.766008
3          70168  Anuppur  2018        2.242118e+07            22.421182
4          70168  Anuppur  2019        2.307636e+07            23.076356

In [360]:
months = list(range(1,13))
grid = []
for _,row in df4_expanded.iterrows():
    for month in months:
        grid.append({
            'district_code': row['district_code'],
            'district': row['district'],
            'year': row['year'],
            'month': month,
            'built_up_area_sq_m': row['built_up_area_sq_m'],
            'built_up_area_sq_km': row['built_up_area_sq_km']
        })

full_grid_df3 = pd.DataFrame(grid)
full_grid_df3.head(5)

,district_code,district,year,month,built_up_area_sq_m,built_up_area_sq_km
0,70168,Anuppur,2015,1,2.045566e+07,20.45566
1,70168,Anuppur,2015,2,2.045566e+07,20.45566
2,70168,Anuppur,2015,3,2.045566e+07,20.45566
3,70168,Anuppur,2015,4,2.045566e+07,20.45566
4,70168,Anuppur,2015,5,2.045566e+07,20.45566

In [361]:
df4_final = pd.merge(df4_expanded,full_grid_df3, on = ['district_code','district','year','built_up_area_sq_m','built_up_area_sq_km'])
df4_final.head(20)

,district_code,district,year,built_up_area_sq_m,built_up_area_sq_km,month
0,70168,Anuppur,2015,2.045566e+07,20.455660,1
1,70168,Anuppur,2015,2.045566e+07,20.455660,2
2,70168,Anuppur,2015,2.045566e+07,20.455660,3
3,70168,Anuppur,2015,2.045566e+07,20.455660,4
4,70168,Anuppur,2015,2.045566e+07,20.455660,5
5,70168,Anuppur,2015,2.045566e+07,20.455660,6
6,70168,Anuppur,2015,2.045566e+07,20.455660,7
7,70168,Anuppur,2015,2.045566e+07,20.455660,8
8,70168,Anuppur,2015,2.045566e+07,20.455660,9
9,70168,Anuppur,2015,2.045566e+07,20.455660,10
10,70168,Anuppur,2015,2.045566e+07,20.455660,11
11,70168,Anuppur,2015,2.045566e+07,20.455660,12
12,70168,Anuppur,2016,2.111083e+07,21.110834,1
13,70168,Anuppur,2016,2.111083e+07,21.110834,2
14,70168,Anuppur,2016,2.111083e+07,21.110834,3
15,70168,Anuppur,2016,2.111083e+07,21.110834,4
16,70168,Anuppur,2016,2.111083e+07,21.110834,5
17,70168,Anuppur,2016,2.111083e+07,21.110834,6
18,70168,Anuppur,2016,2.111083e+07,21.110834,7
19,70168,Anuppur,2016,2.111083e+07,21.110834,8

In [362]:
df4_with_month = df4_final.to_csv('../data/raw/df4_final_with_months.csv', index=False)

In [363]:
df7 = pd.read_csv('../data/raw/df4_final_with_months.csv')
df7.head()

,district_code,district,year,built_up_area_sq_m,built_up_area_sq_km,month
0,70168,Anuppur,2015,2.045566e+07,20.45566,1
1,70168,Anuppur,2015,2.045566e+07,20.45566,2
2,70168,Anuppur,2015,2.045566e+07,20.45566,3
3,70168,Anuppur,2015,2.045566e+07,20.45566,4
4,70168,Anuppur,2015,2.045566e+07,20.45566,5

In [364]:
df_final =pd.merge(df6, df7, on=['district_code','district','year','month'], how='inner')
df_final.head(20)

,district_code,district,year,month,lst,night_lst,ndvi,total_population,built_up_area_sq_m,built_up_area_sq_km
0,70168,Anuppur,2018,1,24.049897,13.472585,0.379674,682752.8,2.242118e+07,22.421182
1,70168,Anuppur,2018,2,31.022090,14.983734,0.347770,682752.8,2.242118e+07,22.421182
2,70168,Anuppur,2018,3,39.598072,19.056348,0.307356,682752.8,2.242118e+07,22.421182
3,70168,Anuppur,2018,4,42.478163,20.937356,0.270313,682752.8,2.242118e+07,22.421182
4,70168,Anuppur,2018,5,42.944661,23.263237,0.274777,682752.8,2.242118e+07,22.421182
5,70168,Anuppur,2018,6,38.789129,25.023293,0.383138,682752.8,2.242118e+07,22.421182
6,70168,Anuppur,2018,7,30.391037,24.055679,0.389486,682752.8,2.242118e+07,22.421182
7,70168,Anuppur,2018,8,30.913989,22.019084,0.489859,682752.8,2.242118e+07,22.421182
8,70168,Anuppur,2018,9,30.536769,21.382662,0.641759,682752.8,2.242118e+07,22.421182
9,70168,Anuppur,2018,10,28.358063,20.087057,0.535852,682752.8,2.242118e+07,22.421182
10,70168,Anuppur,2018,11,29.793593,12.921890,0.441124,682752.8,2.242118e+07,22.421182
11,70168,Anuppur,2018,12,24.175561,12.442541,0.396785,682752.8,2.242118e+07,22.421182
12,70168,Anuppur,2019,1,24.049897,13.472585,0.374438,688273.4,2.307636e+07,23.076356
13,70168,Anuppur,2019,2,30.329219,14.996980,0.351701,688273.4,2.307636e+07,23.076356
14,70168,Anuppur,2019,3,36.633443,18.512734,0.328425,688273.4,2.307636e+07,23.076356
15,70168,Anuppur,2019,4,42.920718,21.689455,0.286473,688273.4,2.307636e+07,23.076356
16,70168,Anuppur,2019,5,45.546204,24.590959,0.288462,688273.4,2.307636e+07,23.076356
17,70168,Anuppur,2019,6,42.550010,26.049268,0.331849,688273.4,2.307636e+07,23.076356
18,70168,Anuppur,2019,7,33.545285,21.609693,0.492996,688273.4,2.307636e+07,23.076356
19,70168,Anuppur,2019,8,29.224766,21.392086,0.522781,688273.4,2.307636e+07,23.076356

In [365]:
final_dataset = df_final.to_csv('../data/processed/final_dataset_for_analysis.csv')

In [366]:
df8 = pd.read_csv('../data/processed/final_dataset_for_analysis.csv')

In [367]:
df9 = pd.read_excel('../data/processed/final_dataset_for_analysis.xlsx')

In [368]:
df9.head()

,Unnamed: 0,district_code,district,year,month,lst,night_lst,ndvi,total_population,built_up_area_sq_m,built_up_area_sq_km,Unnamed: 11,district_area_sq_km
0,0,70168,Anuppur,2018,1,24.049897,13.472585,0.379674,682752.8,2.242118e+07,22.421182,NaN,3746
1,1,70168,Anuppur,2018,2,31.022090,14.983734,0.347770,682752.8,2.242118e+07,22.421182,NaN,3746
2,2,70168,Anuppur,2018,3,39.598072,19.056348,0.307356,682752.8,2.242118e+07,22.421182,NaN,3746
3,3,70168,Anuppur,2018,4,42.478163,20.937356,0.270313,682752.8,2.242118e+07,22.421182,NaN,3746
4,4,70168,Anuppur,2018,5,42.944661,23.263237,0.274777,682752.8,2.242118e+07,22.421182,NaN,3746

In [369]:
df9_clean = df9.drop(columns=['Unnamed: 0', 'Unnamed: 11'],inplace=True)

In [370]:
df9['built_up_pct'] = df9['built_up_area_sq_km']/df9['district_area_sq_km']*100

In [371]:
df9['month_sin'] = np.sin((2*3.14*df9['month'])/12)

In [372]:
df9['month_cos'] = np.cos((3*3.14*df['month'])/12)

In [373]:
df9.head()

,district_code,district,year,month,lst,night_lst,ndvi,total_population,built_up_area_sq_m,built_up_area_sq_km,district_area_sq_km,built_up_pct,month_sin,month_cos
0,70168,Anuppur,2018,1,24.049897,13.472585,0.379674,682752.8,2.242118e+07,22.421182,3746,0.598537,0.499770,0.707388
1,70168,Anuppur,2018,2,31.022090,14.983734,0.347770,682752.8,2.242118e+07,22.421182,3746,0.598537,0.865760,0.000796
2,70168,Anuppur,2018,3,39.598072,19.056348,0.307356,682752.8,2.242118e+07,22.421182,3746,0.598537,1.000000,-0.706262
3,70168,Anuppur,2018,4,42.478163,20.937356,0.270313,682752.8,2.242118e+07,22.421182,3746,0.598537,0.866556,-0.999999
4,70168,Anuppur,2018,5,42.944661,23.263237,0.274777,682752.8,2.242118e+07,22.421182,3746,0.598537,0.501149,-0.708513

In [374]:
df9['lst_lag1'] = (df9.groupby("district_code")["lst"].shift(1))

In [375]:
df9['lst_lag2'] = (df9.groupby("district_code")['lst'].shift(2))

In [376]:
df9['lst_lag3'] = (df9.groupby("district_code")['lst'].shift(3))

In [377]:
df9['lst_3month_avg'] = (df.groupby("district_code")["lst"].transform(lambda x: x.shift(1).rolling(window=3, min_periods=1).mean()))

In [378]:
df9['lst_12month_avg'] = (df.groupby("district_code")["lst"].transform(lambda x: x.shift(1).rolling(window = 12, min_periods = 1).mean()))

In [379]:
df9["target_lst"] = (df9.groupby("district_code")["lst"].shift(-1))

In [380]:
df9.head()

,district_code,district,year,month,lst,night_lst,ndvi,total_population,built_up_area_sq_m,built_up_area_sq_km,district_area_sq_km,built_up_pct,month_sin,month_cos,lst_lag1,lst_lag2,lst_lag3,lst_3month_avg,lst_12month_avg,target_lst
0,70168,Anuppur,2018,1,24.049897,13.472585,0.379674,682752.8,2.242118e+07,22.421182,3746,0.598537,0.499770,0.707388,NaN,NaN,NaN,NaN,NaN,31.022090
1,70168,Anuppur,2018,2,31.022090,14.983734,0.347770,682752.8,2.242118e+07,22.421182,3746,0.598537,0.865760,0.000796,24.049897,NaN,NaN,24.049897,24.049897,39.598072
2,70168,Anuppur,2018,3,39.598072,19.056348,0.307356,682752.8,2.242118e+07,22.421182,3746,0.598537,1.000000,-0.706262,31.022090,24.049897,NaN,27.535993,27.535993,42.478163
3,70168,Anuppur,2018,4,42.478163,20.937356,0.270313,682752.8,2.242118e+07,22.421182,3746,0.598537,0.866556,-0.999999,39.598072,31.022090,24.049897,31.556686,31.556686,42.944661
4,70168,Anuppur,2018,5,42.944661,23.263237,0.274777,682752.8,2.242118e+07,22.421182,3746,0.598537,0.501149,-0.708513,42.478163,39.598072,31.022090,37.699442,34.287055,38.789129

In [381]:
df9.to_excel('../data/final/final_mp_dataset.xlsx')

In [382]:
df10 = pd.read_excel('../data/final/final_mp_dataset.xlsx')

In [383]:
df10.head()

,Unnamed: 0,district_code,district,year,month,lst,night_lst,ndvi,total_population,built_up_area_sq_m,...,district_area_sq_km,built_up_pct,month_sin,month_cos,lst_lag1,lst_lag2,lst_lag3,lst_3month_avg,lst_12month_avg,target_lst
0,0,70168,Anuppur,2018,1,24.049897,13.472585,0.379674,682752.8,2.242118e+07,...,3746,0.598537,0.499770,0.707388,NaN,NaN,NaN,NaN,NaN,31.022090
1,1,70168,Anuppur,2018,2,31.022090,14.983734,0.347770,682752.8,2.242118e+07,...,3746,0.598537,0.865760,0.000796,24.049897,NaN,NaN,24.049897,24.049897,39.598072
2,2,70168,Anuppur,2018,3,39.598072,19.056348,0.307356,682752.8,2.242118e+07,...,3746,0.598537,1.000000,-0.706262,31.022090,24.049897,NaN,27.535993,27.535993,42.478163
3,3,70168,Anuppur,2018,4,42.478163,20.937356,0.270313,682752.8,2.242118e+07,...,3746,0.598537,0.866556,-0.999999,39.598072,31.022090,24.049897,31.556686,31.556686,42.944661
4,4,70168,Anuppur,2018,5,42.944661,23.263237,0.274777,682752.8,2.242118e+07,...,3746,0.598537,0.501149,-0.708513,42.478163,39.598072,31.022090,37.699442,34.287055,38.789129

In [384]:
df10.to_csv('../data/final/final_mp_dataset.csv')

In [385]:
df11 = pd.read_csv('../data/final/final_mp_dataset.csv')

In [386]:
df11.head()

,Unnamed: 0.1,Unnamed: 0,district_code,district,year,month,lst,night_lst,ndvi,total_population,...,district_area_sq_km,built_up_pct,month_sin,month_cos,lst_lag1,lst_lag2,lst_lag3,lst_3month_avg,lst_12month_avg,target_lst
0,0,0,70168,Anuppur,2018,1,24.049897,13.472585,0.379674,682752.8,...,3746,0.598537,0.499770,0.707388,NaN,NaN,NaN,NaN,NaN,31.022090
1,1,1,70168,Anuppur,2018,2,31.022090,14.983734,0.347770,682752.8,...,3746,0.598537,0.865760,0.000796,24.049897,NaN,NaN,24.049897,24.049897,39.598072
2,2,2,70168,Anuppur,2018,3,39.598072,19.056348,0.307356,682752.8,...,3746,0.598537,1.000000,-0.706262,31.022090,24.049897,NaN,27.535993,27.535993,42.478163
3,3,3,70168,Anuppur,2018,4,42.478163,20.937356,0.270313,682752.8,...,3746,0.598537,0.866556,-0.999999,39.598072,31.022090,24.049897,31.556686,31.556686,42.944661
4,4,4,70168,Anuppur,2018,5,42.944661,23.263237,0.274777,682752.8,...,3746,0.598537,0.501149,-0.708513,42.478163,39.598072,31.022090,37.699442,34.287055,38.789129

In [387]:
df11.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'district_code', 'district', 'year',
       'month', 'lst', 'night_lst', 'ndvi', 'total_population',
       'built_up_area_sq_m', 'built_up_area_sq_km', 'district_area_sq_km',
       'built_up_pct', 'month_sin', 'month_cos', 'lst_lag1', 'lst_lag2',
       'lst_lag3', 'lst_3month_avg', 'lst_12month_avg', 'target_lst'],
      dtype='str')

In [388]:
df11.drop(columns = ['Unnamed: 0.1','Unnamed: 0'], inplace=True)

In [389]:
df11.head()

,district_code,district,year,month,lst,night_lst,ndvi,total_population,built_up_area_sq_m,built_up_area_sq_km,district_area_sq_km,built_up_pct,month_sin,month_cos,lst_lag1,lst_lag2,lst_lag3,lst_3month_avg,lst_12month_avg,target_lst
0,70168,Anuppur,2018,1,24.049897,13.472585,0.379674,682752.8,2.242118e+07,22.421182,3746,0.598537,0.499770,0.707388,NaN,NaN,NaN,NaN,NaN,31.022090
1,70168,Anuppur,2018,2,31.022090,14.983734,0.347770,682752.8,2.242118e+07,22.421182,3746,0.598537,0.865760,0.000796,24.049897,NaN,NaN,24.049897,24.049897,39.598072
2,70168,Anuppur,2018,3,39.598072,19.056348,0.307356,682752.8,2.242118e+07,22.421182,3746,0.598537,1.000000,-0.706262,31.022090,24.049897,NaN,27.535993,27.535993,42.478163
3,70168,Anuppur,2018,4,42.478163,20.937356,0.270313,682752.8,2.242118e+07,22.421182,3746,0.598537,0.866556,-0.999999,39.598072,31.022090,24.049897,31.556686,31.556686,42.944661
4,70168,Anuppur,2018,5,42.944661,23.263237,0.274777,682752.8,2.242118e+07,22.421182,3746,0.598537,0.501149,-0.708513,42.478163,39.598072,31.022090,37.699442,34.287055,38.789129

In [391]:
df11['ndvi_builtup_interaction'] = df11['ndvi']*df11['built_up_pct']

In [393]:
df11['population_density'] = df11['total_population']/df11['district_area_sq_km']

In [394]:
df11['built_up_growth'] = df11.groupby('district')['built_up_pct'].diff()

In [396]:
df11['built_up_growth'] = df11['built_up_growth'].fillna(0)

In [401]:
df11['ndvi_annual_average'] = df11.groupby(['district','year'])['ndvi'].transform('mean')

In [407]:
df11['ndvi_anomally'] = df11['ndvi'] - df11['ndvi_annual_average']

In [409]:
df11['district_avg_lst'] = df11.groupby('district')['lst'].transform('mean')

In [413]:
df11['lst_anomally'] = df11['district_avg_lst']-df11.groupby('district')['lst'].shift(1)

In [414]:
df11.head()

,district_code,district,year,month,lst,night_lst,ndvi,total_population,built_up_area_sq_m,built_up_area_sq_km,...,lst_3month_avg,lst_12month_avg,target_lst,ndvi_builtup_interaction,population_density,built_up_growth,ndvi_annual_average,ndvi_anomally,district_avg_lst,lst_anomally
0,70168,Anuppur,2018,1,24.049897,13.472585,0.379674,682752.8,2.242118e+07,22.421182,...,NaN,NaN,31.022090,0.227248,182.261826,0.0,0.404824,-0.025151,31.450169,NaN
1,70168,Anuppur,2018,2,31.022090,14.983734,0.347770,682752.8,2.242118e+07,22.421182,...,24.049897,24.049897,39.598072,0.208153,182.261826,0.0,0.404824,-0.057055,31.450169,7.400272
2,70168,Anuppur,2018,3,39.598072,19.056348,0.307356,682752.8,2.242118e+07,22.421182,...,27.535993,27.535993,42.478163,0.183964,182.261826,0.0,0.404824,-0.097468,31.450169,0.428079
3,70168,Anuppur,2018,4,42.478163,20.937356,0.270313,682752.8,2.242118e+07,22.421182,...,31.556686,31.556686,42.944661,0.161792,182.261826,0.0,0.404824,-0.134511,31.450169,-8.147903
4,70168,Anuppur,2018,5,42.944661,23.263237,0.274777,682752.8,2.242118e+07,22.421182,...,37.699442,34.287055,38.789129,0.164464,182.261826,0.0,0.404824,-0.130047,31.450169,-11.027994

In [415]:
df11.to_csv('../data/final/final_mp_dataset.csv')