In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C://Users//harsh//Desktop//isro hacakthon//data//raw//Delhi_Zone_Monthly_BuiltUp_Percent_2018_2022.csv')

In [4]:
df.head(12)

    zone  year  month  built_up_percent        method
0      1  2018      1         73.000151  extrapolated
1      2  2018      1         57.934250  extrapolated
2      3  2018      1         33.325853  extrapolated
3      4  2018      1         59.896855  extrapolated
4      5  2018      1         59.576301  extrapolated
5      6  2018      1         46.258476  extrapolated
6      7  2018      1         19.153721  extrapolated
7      8  2018      1         61.110141  extrapolated
8      9  2018      1         25.931722  extrapolated
9     10  2018      1         64.323232  extrapolated
10    11  2018      1         67.262516  extrapolated
11    12  2018      1         76.517608  extrapolated

In [5]:
df['zone'].dtype

dtype('int64')

In [7]:
df = df.drop(df[df['zone'] == 12].index)

In [8]:
df.head(12)

    zone  year  month  built_up_percent        method
0      1  2018      1         73.000151  extrapolated
1      2  2018      1         57.934250  extrapolated
2      3  2018      1         33.325853  extrapolated
3      4  2018      1         59.896855  extrapolated
4      5  2018      1         59.576301  extrapolated
5      6  2018      1         46.258476  extrapolated
6      7  2018      1         19.153721  extrapolated
7      8  2018      1         61.110141  extrapolated
8      9  2018      1         25.931722  extrapolated
9     10  2018      1         64.323232  extrapolated
10    11  2018      1         67.262516  extrapolated
12     1  2018      2         73.000151  extrapolated

In [24]:
df['zone'] = df['zone'].astype(int)

In [25]:
df['zone'] = df['zone'].replace({1: 'Central-Zone', 2: 'City-Sadar Paharganj(SP) Zone', 3: 'Civil Lines Zone', 4: 'Karol Bagh Zone', 5: 'Keshav Puram Zone', 6: 'Najafgarh Zone', 7: 'Narela Zone', 8: 'Rohini Zone', 9: 'South Zone', 10: 'West Zone', 11: 'Shahdara South Zone'}, inplace = True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_18396\1980449575.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['zone'] = df['zone'].replace({1: 'Central-Zone', 2: 'City-Sadar Paharganj(SP) Zone', 3: 'Civil Lines Zone', 4: 'Karol Bagh Zone', 5: 'Keshav Puram Zone', 6: 'Najafgarh Zone', 7: 'Narela Zone', 8: 'Rohini Zone', 9: 'South Zone', 10: 'West Zone', 11: 'Shahdara South Zone'}, inplace = True)

In [26]:
df['zone'].unique()

array(['Central-Zone', 'City-Sadar Paharganj(SP) Zone',
       'Civil Lines Zone', 'Karol Bagh Zone', 'Keshav Puram Zone',
       'Najafgarh Zone', 'Narela Zone', 'Rohini Zone', 'South Zone',
       'West Zone', 'Shahdara South Zone'], dtype=object)

In [35]:
zone_ward_mapping = {
    'Narela Zone': ['Narela','Bankner','Holambi Kalan','Alipur','Begumpur','Shahbad Dairy','Pooth Khurd','Nangloi'],
    'Rohini Zone': ['Pooth Kalan','Begumpur','Shahbad Daulatpur','Pitampura','Saraswati Vihar','Nimri Colony','Wazirpur','Ashok Vihar','Tri Nagar','Rampura','Shakur Pur','Sultanpuri A','Sutanpuri B','Sultanpuri C','Sultanpuri East','Sultanpur Majra','Mangolpuri A','Mangolpuri B','Mangolpuri C','Rohini Sector 21','Rohini Sector 22','Rohini Sector 23','ward_a','ward_b','ward_c','ward_d','ward_e','ward_f','ward_g','ward_h','ward_i','ward_j'],
    'Civil Lines Zone': ['Burari','Kadipur','Mukundpur','Sant Nagar', 'Jharoda', 'Bhalswa', 'Jahangirpuri', 'Samaypur Badli', 'Adarsh Nagar', 'Azadpur', 'Model Town','Dhirpur', 'G.T.B Nagar', 'Vijay Nagar', 'Civil Lines', 'Malka Ganj', 'Timarpur', 'Mukherjee Nagar', 'Wazirabad', 'Majnu Ka Tila', 'Ward_1_civil_lines', 'Ward_2_civil_lines'],
    'Karol Bagh Zone': ['Rohini Central', 'Rohini North', 'Rohini South', 'Budh Vihar', 'Pooth Khurd', 'Bawana', 'Nangal Thakran', 'Kanjhawala', 'Rani Khera', 'Mubarakpur Dabas', 'Kirari Suleman Nagar','Prem Nagar', 'Nithari', 'Karol_Bagh_ward_1', 'Karol_Bagh_ward_2', 'Karol_Bagh_ward_3', 'Karol_Bagh_ward_4', 'Karol_Bagh_ward_5', 'Karol_Bagh_ward_6', 'Karol_Bagh_ward_7', 'Karol_Bagh_ward_8', 'Karol_Bagh_ward_9','Karol_Bagh_ward_10', 'Karol_Bagh_ward_11', 'Karol_Bagh_ward_12', 'Karol_Bagh_ward_13'],
    'West Zone': ['Aman Vihar', 'Kirari', 'Pratap Vihar', 'Sultanpuri North', 'Jawalpuri', 'Nihal Vihar', 'Guru Harikishan Nagar', 'Pashchim Vihar', 'Peeragarhi', 'Nangloi Jat', 'Quammruddin Nagar','Chander Vihar', 'Meerabagh', 'Keshopur', 'Tilak Nagar', 'Khyala', 'Vishnu Garden', 'Rajouri Garden', 'Tagore Garden', 'Raghubir Nagar', 'Madipur', 'Punjabi Bagh','West Patel Nagar', 'East Patel Nagar', 'Ranjit Nagar', 'Karampura', 'Moti Nagar', 'Ramesh Nagar', 'Sharda Puri', 'Kirti Nagar', 'Hari Nagar', 'Subhash Nagar', 'Mayapuri','Mansarovar Garden', 'Janakpuri Garden'],
    'Central-Zone': ['Isapur', 'Dhansa', 'Mundka', 'Nilothi', 'Nangloi', 'Karala', 'Ladpur', 'Tikri Kalan', 'Jharoda Kalan', 'Kapashera', 'Bijwasan','Mahipalpur', 'Raj Nagar', 'Palam', 'Sadh Nagar', 'Mahavir Enclave', 'Madhu Vihar', 'Manglapuri Extension', 'Dwarka Sector 3', 'Dwarka Sector 8', 'Nasirpur', 'Dashrath Puri','Bindanpur', 'Jeewan Park', 'Uttam Nagar East', 'Mundka', 'Nilothi', 'Nangloi', 'Karala'],
    'South Zone': ['Janakpuri West', 'Nangal Raya', 'Hari Nagar A', 'Fateh Nagar', 'Mehrauli', 'Vasant Kunj', 'Kishangarh', 'Lado Sarai', 'Said-ul-Ajaib', 'Deoli', 'Tigri','Sangam Vihar A', 'Sangam Vihar B', 'Sangam Vihar C', 'Sangam Vihar D', 'Sangam Vihar E', 'Khanpur', 'Ambedkar Nagar', 'Madangir', 'Pushp Vihar', 'Tughlakabad Extension', 'Tughlakabad','Cherag Delhi', 'Shahpur Jat', 'Malviya Nagar', 'South Zone ward 1'],
    'City-Sadar Paharganj(SP) Zone': ['Hauz Khas', 'Safdarganj Enclave', 'Green Park', 'Munrika', 'RK Puram', 'Vasant Vihar', 'Greater Kailash', 'Chittaranjan Park', 'Alaknanda', 'Kalkaji', 'Govindpuri','Harkesh Nagar', 'Okhla', 'Madanpur Khadar East', 'Madanpur Khadar West', 'Janakpuri East', 'Milap Nagar', 'Sitapuri', 'Roshanpura', 'Ladpur', 'Tikri Kalan', 'Jharoda Kalan','Kapashera', 'Bijwasan', 'Mahipalpur', 'Raj Nagar', 'Palam', 'Sadh Nagar', 'Mahavir Enclave', 'Madhu Vihar', 'Manglapuri Extension', 'Dwarka Sector 3', 'Dwarka Sector 8'],
    'Shahdara South Zone': ['Andrews Ganj','Amar Colony','Kotla Mubarakpur','Defence Colony','Jangpura','Nizamuddin','Bhogal', 'Sidhartha Nagar', 'Lajpat Nagar East', 'Daryaganj', 'Bazar Sita Ram'],
    'Keshav Puram Zone': ['Vishwas Nagar','IP Extension','Preet Vihar','Patparganj','Mayur Vihar Phase1','Trilokpuri','New Ashok Nagar', 'Kalyanpuri', 'Khichripur'],
    'Najafgarh Zone': ['Dabri','Sagarpur','Manglapuri','Dwarka A','Dwarka B','Dwarka C','Nawada','Uttam Nagar','Bindra Pur','Matiala','Mohan Garden','Hasta','Vikas Puri','Kunwar Singh Nagar','Chander Vihar Extension','Baprola','Sainik Enclave','Nangli Sakrawati','Kakrola','Najafgarh','Dichaon Kalan']

}
df['ward'] = df['zone'].map(zone_ward_mapping)
expanded_df = df.explode('ward').reset_index(drop=True)
column_order = ['zone', 'ward', 'year', 'month', 'built_up_percent', 'method']
expanded_df = expanded_df[column_order]

In [36]:
expanded_df.head()

           zone     ward  year  month  built_up_percent        method
0  Central-Zone   Isapur  2018      1         73.000151  extrapolated
1  Central-Zone   Dhansa  2018      1         73.000151  extrapolated
2  Central-Zone   Mundka  2018      1         73.000151  extrapolated
3  Central-Zone  Nilothi  2018      1         73.000151  extrapolated
4  Central-Zone  Nangloi  2018      1         73.000151  extrapolated

In [37]:
df2 = pd.read_csv('C://Users//harsh//Desktop//isro hacakthon//data//raw//Delhi_wardwise_lst_and_ndvi_2018_to_2025.csv')

In [38]:
df2.head()

,Unnamed: 0,zone,ward,colony,year,month,mean_ndvi,method,pixel_count_ndvi,valid_pixel_count_ndvi,cloud_pixel_percent,mean_lst_day_celsius,pixel_count_lst,valid_pixel_count_lst,invalid_pixel_percent
0,0,Central-Zone,Bijwasan,741,2018,1,0.090003,computed,1557.0,1557.0,0.0,21.874039,156,156,0.0
1,1,Central-Zone,Bijwasan,741,2018,2,0.100894,interpolated,1557.0,1557.0,0.0,25.035503,156,156,0.0
2,2,Central-Zone,Bijwasan,741,2018,3,0.111785,computed,1557.0,1557.0,0.0,33.572937,156,156,0.0
3,3,Central-Zone,Bijwasan,741,2018,4,0.116212,interpolated,1557.0,1557.0,0.0,44.439710,156,156,0.0
4,4,Central-Zone,Bijwasan,741,2018,5,0.120639,computed,1557.0,1557.0,0.0,44.807560,156,156,0.0

In [39]:
df2 = df2.drop(columns = ['colony'])

In [40]:
df2.head()

,Unnamed: 0,zone,ward,year,month,mean_ndvi,method,pixel_count_ndvi,valid_pixel_count_ndvi,cloud_pixel_percent,mean_lst_day_celsius,pixel_count_lst,valid_pixel_count_lst,invalid_pixel_percent
0,0,Central-Zone,Bijwasan,2018,1,0.090003,computed,1557.0,1557.0,0.0,21.874039,156,156,0.0
1,1,Central-Zone,Bijwasan,2018,2,0.100894,interpolated,1557.0,1557.0,0.0,25.035503,156,156,0.0
2,2,Central-Zone,Bijwasan,2018,3,0.111785,computed,1557.0,1557.0,0.0,33.572937,156,156,0.0
3,3,Central-Zone,Bijwasan,2018,4,0.116212,interpolated,1557.0,1557.0,0.0,44.439710,156,156,0.0
4,4,Central-Zone,Bijwasan,2018,5,0.120639,computed,1557.0,1557.0,0.0,44.807560,156,156,0.0

In [42]:
for name, df_check in [("df", df), ("df2", df2)]:
    for col in ['zone', 'ward', 'year', 'month']:
        # Check if any row in the column is a list
        has_list = df_check[col].apply(lambda x: isinstance(x, list)).any()
        if has_list:
            print(f"⚠️ Found lists in DataFrame '{name}', column '{col}'")

⚠️ Found lists in DataFrame 'df', column 'ward'

In [43]:
merged_df = pd.merge(expanded_df, df2, on=['zone','ward','year','month'],how='inner',suffixes = ('_ndvi_and_lst','_builtpct'))

In [44]:
merged_df.head()

,zone,ward,year,month,built_up_percent,method_ndvi_and_lst,Unnamed: 0,mean_ndvi,method_builtpct,pixel_count_ndvi,valid_pixel_count_ndvi,cloud_pixel_percent,mean_lst_day_celsius,pixel_count_lst,valid_pixel_count_lst,invalid_pixel_percent
0,Central-Zone,Isapur,2018,1,73.000151,extrapolated,4182,0.167839,computed,9489.0,9407.0,0.864158,22.010773,1020,1020,0.0
1,Central-Zone,Isapur,2018,1,73.000151,extrapolated,4233,0.191710,computed,882.0,882.0,0.000000,22.035280,88,88,0.0
2,Central-Zone,Isapur,2018,1,73.000151,extrapolated,4284,0.090713,computed,423.0,423.0,0.000000,21.701395,40,40,0.0
3,Central-Zone,Dhansa,2018,1,73.000151,extrapolated,2907,0.173002,computed,6764.0,6744.0,0.295683,21.955961,727,727,0.0
4,Central-Zone,Mundka,2018,1,73.000151,extrapolated,8313,0.104475,computed,1237.0,1222.0,1.212611,20.400532,125,125,0.0

In [45]:
merged_df.to_csv('C://Users//harsh//Desktop//isro hacakthon//data//raw//Delhi_wardwise_lst_and_ndvi_and_builtup_2018_to_2025.csv')